[package]
name = "pomo"
version = "0.1.0"
authors = ["eleijonmarck <eric.leijonmarck@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustbox = "*"
notify-rust = "4"
rodio = "0.13.0"
